"""empty message

Revision ID: 70a9bf0bef45
Revises: c3537dc3dde7
Create Date: 2023-09-12 12:03:46.745737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a9bf0bef45'
down_revision = 'c3537dc3dde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_certificates_instructor_id_instructors'), 'instructors', ['instructor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_certificates_instructor_id_instructors'), type_='foreignkey')
        batch_op.drop_column('instructor_id')

    # ### end Alembic commands ###
